name: audio_example
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.7
  stream_video_flutter:
    path:
      ../stream-video-flutter/packages/stream_video_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  stream_video:
    path:
      ../stream-video-flutter/packages/stream_video
  stream_video_flutter:
    path:
      ../stream-video-flutter/packages/stream_video_flutter

flutter:
  uses-material-design: true
